import { randomUUID } from "node:crypto";

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import Fastify from "../apps/server/node_modules/fastify/fastify.js";
import type { FastifyInstance } from "../apps/server/node_modules/fastify";

import { loadConfig } from "../apps/server/src/config.js";
import {
  closeDb,
  initDb,
  migrateDb,
  type AppDatabase
} from "../apps/server/src/db/index.js";
import { DrizzleMemoryRepository } from "../apps/server/src/db/repositories/memory-repository.js";
import { DrizzleMessageRepository } from "../apps/server/src/db/repositories/message-repository.js";
import { DrizzleSessionRepository } from "../apps/server/src/db/repositories/session-repository.js";
import { SessionService } from "../apps/server/src/services/session.js";
import { registerMemoryRoutes } from "../apps/server/src/routes/memories.js";
import { registerSearchRoutes } from "../apps/server/src/routes/search.js";
import { registerSkillRoutes } from "../apps/server/src/routes/skills.js";
import { registerThreadRoutes } from "../apps/server/src/routes/threads.js";

let app: FastifyInstance;
let db: AppDatabase;

beforeEach(async () => {
  db = initDb({ dbPath: ":memory:" });
  migrateDb(db);

  app = Fastify();
  app.decorate("infra", {
    config: loadConfig({ env: {}, cwd: "/tmp" }),
    sentryClient: {} as never,
    waveClient: undefined,
    db,
    skills: [
      {
        name: "memory-management",
        description: "Use the alma CLI to manage long-term memory.",
        content: "# Memory Management",
        filePath: "/tmp/skills/memory-management/SKILL.md",
        source: "project"
      }
    ]
  });
  app.decorate("services", {} as never);

  registerSearchRoutes(app);
  registerMemoryRoutes(app);
  registerSkillRoutes(app);
  registerThreadRoutes(app);

  await app.ready();
});

afterEach(async () => {
  await app.close();
  closeDb(db);
});

describe("Phase 4 API routes", () => {
  it("searches threads across titles and indexed message text without duplicates", async () => {
    const sessionRepo = new DrizzleSessionRepository(db);
    const messageRepo = new DrizzleMessageRepository(db);
    const thread = sessionRepo.create({
      id: randomUUID(),
      sessionKey: "thread:react",
      title: "React debugging"
    });

    messageRepo.create({
      id: randomUUID(),
      sessionId: thread.id,
      role: "user",
      content: "React component crash",
      searchText: "React component crash"
    });

    const response = await app.inject({
      method: "GET",
      url: "/api/v1/search/threads?q=React"
    });

    expect(response.statusCode).toBe(200);
    expect(response.json()).toEqual([
      expect.objectContaining({
        id: thread.id,
        title: "React debugging",
        messageCount: 1,
        snippet: "React component crash"
      })
    ]);
  });

  it("returns memory stats in the Alma-aligned shape", async () => {
    const memoryRepo = new DrizzleMemoryRepository(db);
    memoryRepo.save({
      id: randomUUID(),
      content: "User prefers concise answers",
      category: "user"
    });
    memoryRepo.save({
      id: randomUUID(),
      content: "Project uses Drizzle ORM",
      category: "project"
    });

    const response = await app.inject({
      method: "GET",
      url: "/api/v1/memories/stats"
    });

    expect(response.statusCode).toBe(200);
    expect(response.json()).toEqual({
      count: 2,
      manualAdded: 2,
      autoGenerated: 0,
      byCategory: {
        user: 1,
        preference: 0,
        project: 1,
        decision: 0,
        knowledge: 0
      },
      embedding: {
        ready: 0,
        pending: 2
      }
    });
  });

  it("returns loaded skills as read-only summaries", async () => {
    const response = await app.inject({
      method: "GET",
      url: "/api/v1/skills"
    });

    expect(response.statusCode).toBe(200);
    expect(response.json()).toEqual([
      {
        id: "memory-management",
        name: "memory-management",
        description: "Use the alma CLI to manage long-term memory.",
        source: "project",
        enabled: true
      }
    ]);
  });

  it("compacts older thread messages into a persisted summary", async () => {
    const sessionRepo = new DrizzleSessionRepository(db);
    const messageRepo = new DrizzleMessageRepository(db);
    const thread = sessionRepo.create({
      id: randomUUID(),
      sessionKey: "thread:compact",
      title: "Long conversation"
    });

    const contents = [
      ["user", "First user request"],
      ["assistant", "First assistant reply"],
      ["user", "Second user request"],
      ["assistant", "Second assistant reply"],
      ["user", "Third user request"],
      ["assistant", "Third assistant reply"],
      ["user", "Fourth user request"],
      ["assistant", "Fourth assistant reply"],
      ["user", "Fifth user request"],
      ["assistant", "Fifth assistant reply"],
      ["user", "Sixth user request"],
      ["assistant", "Sixth assistant reply"]
    ] as const;

    for (const [role, content] of contents) {
      messageRepo.create({
        id: randomUUID(),
        sessionId: thread.id,
        role,
        content,
        searchText: content
      });
    }

    const compactResponse = await app.inject({
      method: "POST",
      url: `/api/v1/threads/${thread.id}/compact`
    });

    expect(compactResponse.statusCode).toBe(200);
    expect(compactResponse.json()).toMatchObject({
      success: true,
      compacted: true,
      trigger: "manual",
      coveredMessageCount: 4,
      preservedTailMessageCount: 8,
      estimatedTokensBefore: expect.any(Number),
      estimatedTokensAfter: expect.any(Number),
      compactionId: expect.any(String),
      thread: {
        id: thread.id,
        messageCount: 12
      }
    });

    const messagesResponse = await app.inject({
      method: "GET",
      url: `/api/v1/threads/${thread.id}/messages`
    });

    expect(messagesResponse.statusCode).toBe(200);

    const compactedMessages = messagesResponse.json() as Array<{
      role: string;
      content: string;
      metadata: string;
    }>;

    expect(compactedMessages).toHaveLength(12);
    expect(compactedMessages.map((message) => message.content)).toEqual([
      "First user request",
      "First assistant reply",
      "Second user request",
      "Second assistant reply",
      "Third user request",
      "Third assistant reply",
      "Fourth user request",
      "Fourth assistant reply",
      "Fifth user request",
      "Fifth assistant reply",
      "Sixth user request",
      "Sixth assistant reply"
    ]);

    const sessionService = new SessionService(
      new DrizzleSessionRepository(db),
      new DrizzleMessageRepository(db)
    );
    const modelHistory = sessionService.buildModelHistory(db, thread.id);

    expect(modelHistory).toHaveLength(9);
    expect(modelHistory[0]).toMatchObject({
      role: "system",
      content: expect.stringContaining("Conversation summary")
    });
    expect(modelHistory[0]!.content).toContain("First user request");
    expect(modelHistory.slice(1).map((message) => message.content)).toEqual([
      "Third user request",
      "Third assistant reply",
      "Fourth user request",
      "Fourth assistant reply",
      "Fifth user request",
      "Fifth assistant reply",
      "Sixth user request",
      "Sixth assistant reply"
    ]);
  });

  it("returns a no-op compact result for short threads", async () => {
    const sessionRepo = new DrizzleSessionRepository(db);
    const messageRepo = new DrizzleMessageRepository(db);
    const thread = sessionRepo.create({
      id: randomUUID(),
      sessionKey: "thread:short",
      title: "Short conversation"
    });

    for (const content of ["One", "Two", "Three"]) {
      messageRepo.create({
        id: randomUUID(),
        sessionId: thread.id,
        role: content === "Two" ? "assistant" : "user",
        content,
        searchText: content
      });
    }

    const response = await app.inject({
      method: "POST",
      url: `/api/v1/threads/${thread.id}/compact`
    });

    expect(response.statusCode).toBe(200);
    expect(response.json()).toMatchObject({
      success: true,
      compacted: false,
      trigger: "manual",
      coveredMessageCount: 0,
      preservedTailMessageCount: 3,
      estimatedTokensBefore: expect.any(Number),
      estimatedTokensAfter: expect.any(Number),
      thread: {
        id: thread.id,
        messageCount: 3
      }
    });
  });
});
