import { sql, eq } from "drizzle-orm";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import type { MemoryRecord, MemoryStats } from "@eva/shared";

import { backfillPendingEmbeddings, embedAndStoreMemory } from "../services/memory-embedding.js";

import {
  DrizzleMemoryRepository,
  type Memory
} from "../db/repositories/memory-repository.js";
import { memories, memoryCategories } from "../db/schema.js";

const memoryCategoryEnum = z.enum([
  "user",
  "preference",
  "project",
  "decision",
  "knowledge"
]);

export const registerMemoryRoutes = (app: FastifyInstance): void => {
  const getRepo = () => new DrizzleMemoryRepository(app.infra.db);
  const toApiMemory = (memory: Memory): MemoryRecord => ({
    id: memory.id,
    category: memory.category,
    origin: memory.origin,
    content: memory.content,
    metadata: memory.metadata,
    sourceThreadId: memory.sourceSessionId,
    sourceMessageId: memory.sourceMessageId,
    createdAt: memory.createdAt,
    updatedAt: memory.updatedAt
  });

  // List all memories
  app.get("/api/v1/memories", async (): Promise<readonly MemoryRecord[]> =>
    getRepo().listAll().map((memory) => toApiMemory(memory))
  );

  app.get("/api/v1/memories/stats", async (): Promise<MemoryStats> => {
    const countRow = app.infra.db
      .select({
        count: sql<number>`count(*)`
      })
      .from(memories)
      .where(eq(memories.userId, "default"))
      .get();

    const grouped = app.infra.db
      .select({
        category: memories.category,
        count: sql<number>`count(*)`
      })
      .from(memories)
      .where(eq(memories.userId, "default"))
      .groupBy(memories.category)
      .all();

    const byCategory = Object.fromEntries(
      memoryCategories.map((category) => [category, 0])
    ) as Record<(typeof memoryCategories)[number], number>;

    for (const row of grouped) {
      byCategory[row.category] = Number(row.count ?? 0);
    }

    const originGrouped = app.infra.db
      .select({
        origin: memories.origin,
        count: sql<number>`count(*)`
      })
      .from(memories)
      .where(eq(memories.userId, "default"))
      .groupBy(memories.origin)
      .all();

    let autoGenerated = 0;
    let manualAdded = 0;
    for (const row of originGrouped) {
      if (row.origin === "tool_saved") autoGenerated = Number(row.count ?? 0);
      else manualAdded = Number(row.count ?? 0);
    }

    const count = Number(countRow?.count ?? 0);

    return {
      count,
      autoGenerated,
      manualAdded,
      byCategory,
      embedding: {
        ready: count - Number(
          app.infra.db
            .select({ c: sql<number>`count(*)` })
            .from(memories)
            .where(eq(memories.embeddingStatus, "pending"))
            .get()?.c ?? 0
        ),
        pending: Number(
          app.infra.db
            .select({ c: sql<number>`count(*)` })
            .from(memories)
            .where(eq(memories.embeddingStatus, "pending"))
            .get()?.c ?? 0
        )
      }
    };
  });

  // Search memories
  app.post("/api/v1/memories/search", async (request): Promise<readonly MemoryRecord[]> => {
    const { query } = z.object({ query: z.string() }).parse(request.body ?? {});
    return getRepo().search(query).map((memory) => toApiMemory(memory));
  });

  // Add a memory
  app.post("/api/v1/memories", async (request) => {
    const { content, category } = z
      .object({
        content: z.string(),
        category: memoryCategoryEnum.optional()
      })
      .parse(request.body ?? {});

    const memory = getRepo().save({
      id: crypto.randomUUID(),
      content,
      origin: "manual",
      ...(category !== undefined ? { category } : {})
    });

    // Fire-and-forget: embed the new memory
    embedAndStoreMemory(app.infra.db, app.infra.config, memory.id, content).catch(() => {});

    return toApiMemory(memory);
  });

  // Update a memory
  app.put("/api/v1/memories/:id", async (request, reply) => {
    const { id } = request.params as { id: string };
    const { content, category } = z
      .object({
        content: z.string(),
        category: memoryCategoryEnum.optional()
      })
      .parse(request.body ?? {});

    const updated = getRepo().update(id, content, category);

    if (!updated) {
      reply.code(404);
      return { error: "Memory not found" };
    }

    return toApiMemory(updated);
  });

  // Delete a memory
  app.delete("/api/v1/memories/:id", async (request, reply) => {
    const { id } = request.params as { id: string };
    const deleted = getRepo().deleteById(id);

    if (!deleted) {
      reply.code(404);
      return { error: "Memory not found" };
    }

    reply.code(204);
    return null;
  });

  // Reindex: batch-embed pending memories
  app.post("/api/v1/memories/reindex", async () => {
    const result = await backfillPendingEmbeddings(app.infra.db, app.infra.config);
    return result;
  });
};
