export type UnknownRecord = Record<string, unknown>;

export type ProviderType =
  | "openai"
  | "anthropic"
  | "google"
  | "aihubmix"
  | "openrouter"
  | "deepseek"
  | "copilot"
  | "azure"
  | "moonshot"
  | "custom"
  | "acp"
  | "claude-subscription"
  | "zai-coding-plan"
  | "kimi-coding-plan";

export interface ProviderModelCapabilities {
  vision?: boolean;
  imageOutput?: boolean;
  functionCalling?: boolean;
  functionCallingViaXml?: boolean;
  jsonMode?: boolean;
  streaming?: boolean;
  reasoning?: boolean;
  contextWindow?: number;
  maxOutputTokens?: number;
}

export interface ProviderModel {
  id: string;
  name: string;
  capabilities?: ProviderModelCapabilities;
  isManual?: boolean;
  providerOptions?: Record<string, unknown>;
}

export interface Provider {
  id: string;
  name: string;
  type: ProviderType;
  models: readonly ProviderModel[];
  availableModels: readonly ProviderModel[];
  hasApiKey: boolean;
  baseURL?: string;
  apiVersion?: string;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ProviderConnectionTestResult {
  success: boolean;
  latencyMs?: number;
  error?: string;
}

export interface ProviderModelsPayload {
  data: readonly string[];
  models: readonly ProviderModel[];
}

export interface ModelSummary {
  id: string;
  name: string;
  provider: string;
  providerId: string;
  capabilities?: ProviderModelCapabilities;
}

export interface AppSettings {
  general: {
    language: "zh" | "en";
    theme: "light" | "dark" | "system";
  };
  chat: {
    defaultModel: string;
    temperature: number;
    streamResponse: boolean;
    autoSaveHistory: boolean;
    historyRetentionDays: number;
    showTokenUsage: boolean;
    enableMarkdown: boolean;
    modelUsageHistory: Record<string, number>;
    defaultToolSelection: "auto" | "all" | "none";
    defaultSkillSelection: "auto" | "all" | "none";
    autoCompact: boolean;
    autoCompactTokenThreshold: number;
    autoCompactMessageThreshold: number;
  };
  security: {
    encryptApiKeys: boolean;
    requirePassword: boolean;
    sessionTimeout: number;
    enableLogging: boolean;
    logLevel: "error" | "warn" | "info" | "debug";
    autoApproveToolRequests: boolean;
  };
  memory: {
    enabled: boolean;
    autoSummarize: boolean;
    autoRetrieve: boolean;
    queryRewriting: boolean;
    maxRetrievedMemories: number;
    similarityThreshold: number;
    embedding: {
      baseUrl: string;
      apiKey: string;
      model: string;
    };
    toolModel?: string;
  };
  toolModel: {
    model?: string;
  };
  webSearch: {
    engine: "google" | "xiaohongshu";
  };
}

export interface HealthStatus {
  status: "ok";
  timestamp: string;
}

export interface ThreadSummary {
  id: string;
  title: string;
  model: string | null;
  origin: string;
  updatedAt: string;
  messageCount: number;
}

export interface ThreadSearchResult {
  id: string;
  title: string;
  updatedAt: string;
  messageCount: number;
  snippet?: string;
}

import type { EvaUIMessage } from "./ui-message.js";

export interface ThreadMessage {
  id: string;
  role: "user" | "assistant";
  message: EvaUIMessage;
  runId: string | null;
  createdAt: string;
}

export type MemoryCategory =
  | "user"
  | "preference"
  | "project"
  | "decision"
  | "knowledge";

export type MemoryOrigin = "manual" | "tool_saved";

export interface MemoryRecord {
  id: string;
  category: MemoryCategory;
  origin: MemoryOrigin;
  content: string;
  metadata: string;
  sourceThreadId: string | null;
  sourceMessageId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface MemoryStats {
  count: number;
  autoGenerated: number;
  manualAdded: number;
  byCategory: Record<MemoryCategory, number>;
  embedding: {
    ready: number;
    pending: number;
  };
}

export type SkillSource = "bundled" | "project";

export interface SkillSummary {
  id: string;
  name: string;
  description: string;
  source: SkillSource;
  enabled: boolean;
}

export const isRecord = (value: unknown): value is UnknownRecord =>
  typeof value === "object" && value !== null;

export const toRecord = (value: unknown): UnknownRecord =>
  isRecord(value) ? value : {};

export const asString = (value: unknown, fallback = ""): string =>
  typeof value === "string" ? value : fallback;

export const optionalString = (value: unknown): string | undefined =>
  typeof value === "string" && value.length > 0 ? value : undefined;

export const toErrorMessage = (error: unknown): string =>
  error instanceof Error ? error.message : "Unknown error";

export * from "./stream-events.js";
export * from "./ui-message.js";
export * from "./ui-message-builder.js";
