import { eq, sql } from "drizzle-orm";
import type { MemoryRecord, MemoryStats } from "@eva/shared";

import type { AppConfig } from "../config.js";
import type { AppDatabase } from "../db/index.js";
import type { DrizzleMemoryRepository, Memory } from "../db/repositories/memory-repository.js";
import { memories, memoryCategories } from "../db/schema.js";
import {
  backfillPendingEmbeddings,
  embedAndStoreMemory
} from "../services/memory/memory-embedding.js";

export type MemoryCategory = (typeof memoryCategories)[number];

/** 落库行 → 线协议。`sourceSessionId` 在对外契约里叫 `sourceThreadId`(UI 说「会话」)。 */
const toRecord = (memory: Memory): MemoryRecord => ({
  id: memory.id,
  category: memory.category,
  origin: memory.origin,
  content: memory.content,
  metadata: memory.metadata,
  sourceThreadId: memory.sourceSessionId,
  sourceMessageId: memory.sourceMessageId,
  createdAt: memory.createdAt,
  updatedAt: memory.updatedAt
});

export interface MemoryApi {
  list(): readonly MemoryRecord[];
  search(query: string): readonly MemoryRecord[];
  /** 存一条手工记忆。向量化是 fire-and-forget —— 嵌入失败不该让保存失败。 */
  add(content: string, category?: MemoryCategory): MemoryRecord;
  update(id: string, content: string, category?: MemoryCategory): MemoryRecord | undefined;
  delete(id: string): boolean;
  stats(): MemoryStats;
  /** 批量补齐 pending 的向量。 */
  reindex(): Promise<{ readonly processed: number; readonly remaining: number }>;
}

export const createMemoryApi = (deps: {
  readonly db: AppDatabase;
  readonly config: AppConfig;
  readonly memories: DrizzleMemoryRepository;
}): MemoryApi => {
  /** 所有统计都限 userId="default" —— 单用户单机,这一列是给将来留的位。 */
  const pendingCount = (): number =>
    Number(
      deps.db
        .select({ c: sql<number>`count(*)` })
        .from(memories)
        .where(eq(memories.embeddingStatus, "pending"))
        .get()?.c ?? 0
    );

  return {
    list: () => deps.memories.listAll().map(toRecord),

    search: (query) => deps.memories.search(query).map(toRecord),

    add: (content, category) => {
      const memory = deps.memories.save({
        id: crypto.randomUUID(),
        content,
        origin: "manual",
        ...(category !== undefined ? { category } : {})
      });

      // fire-and-forget:嵌入要走一次网络,失败只让这条记忆停在 pending,
      // 下次 reindex 会补 —— 绝不让「保存记忆」这个动作因此失败。
      embedAndStoreMemory(deps.db, deps.config, memory.id, content).catch(() => {});

      return toRecord(memory);
    },

    update: (id, content, category) => {
      const updated = deps.memories.update(id, content, category);
      return updated ? toRecord(updated) : undefined;
    },

    delete: (id) => deps.memories.deleteById(id),

    stats: () => {
      const total = Number(
        deps.db
          .select({ count: sql<number>`count(*)` })
          .from(memories)
          .where(eq(memories.userId, "default"))
          .get()?.count ?? 0
      );

      const byCategory = Object.fromEntries(
        memoryCategories.map((category) => [category, 0])
      ) as Record<MemoryCategory, number>;

      for (const row of deps.db
        .select({ category: memories.category, count: sql<number>`count(*)` })
        .from(memories)
        .where(eq(memories.userId, "default"))
        .groupBy(memories.category)
        .all()) {
        byCategory[row.category] = Number(row.count ?? 0);
      }

      let autoGenerated = 0;
      let manualAdded = 0;
      for (const row of deps.db
        .select({ origin: memories.origin, count: sql<number>`count(*)` })
        .from(memories)
        .where(eq(memories.userId, "default"))
        .groupBy(memories.origin)
        .all()) {
        if (row.origin === "tool_saved") autoGenerated = Number(row.count ?? 0);
        else manualAdded = Number(row.count ?? 0);
      }

      // pending 只查一次 —— 原先 route 里同一条 count 查了两遍(ready 与 pending 各一次)。
      const pending = pendingCount();

      return {
        count: total,
        autoGenerated,
        manualAdded,
        byCategory,
        embedding: { ready: total - pending, pending }
      };
    },

    reindex: () => backfillPendingEmbeddings(deps.db, deps.config)
  };
};
